# Logistic Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 27)

In [4]:
print(X_test)

[[    20  74000]
 [    47  49000]
 [    38  65000]
 [    31  18000]
 [    38  55000]
 [    41  30000]
 [    35  53000]
 [    27  57000]
 [    19  21000]
 [    53  82000]
 [    42  90000]
 [    42  54000]
 [    30 116000]
 [    30  49000]
 [    35  57000]
 [    42  65000]
 [    39  73000]
 [    56  60000]
 [    33  69000]
 [    52  21000]
 [    46  59000]
 [    22  27000]
 [    32 120000]
 [    49  74000]
 [    39  79000]
 [    31  76000]
 [    26  72000]
 [    39 134000]
 [    40  60000]
 [    37 144000]
 [    33  31000]
 [    50  44000]
 [    19  70000]
 [    45  79000]
 [    46  74000]
 [    34  43000]
 [    60 102000]
 [    40  47000]
 [    35  44000]
 [    26 118000]
 [    27  31000]
 [    57  33000]
 [    34  43000]
 [    30  87000]
 [    39  75000]
 [    47 107000]
 [    46  32000]
 [    49  28000]
 [    49  39000]
 [    25  33000]
 [    41  63000]
 [    32 100000]
 [    59 130000]
 [    40  65000]
 [    24  55000]
 [    42  64000]
 [    20  86000]
 [    42 108000]
 [    35  2200

In [5]:
print(y_test)

[0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 1
 0 0 0 0 1 0 0 1 1 1 1 1 0 0 1 1 0 0 0 0 1 0 1 1 0 1 0 1 0 1 0 0 0 0 1 1 0
 0 0 1 0 0 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 0 1 1 0 0]


## Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
print(X_train)

[[ 1.37486251  0.55861668]
 [-0.4345848  -0.79264343]
 [ 0.04158554  0.01236259]
 [ 0.13681961  0.01236259]
 [-0.05364853 -0.39014042]
 [ 1.85103286 -1.28139709]
 [ 1.85103286  1.47862356]
 [-1.48215956 -0.44764085]
 [-0.14888259 -0.30388977]
 [-1.29169142 -1.48264859]
 [ 0.99392623  1.82362614]
 [-0.91075515 -0.33263999]
 [ 0.23205368  0.2136141 ]
 [-0.81552108 -0.67764257]
 [-0.62505294 -0.07388805]
 [-0.05364853 -1.08014558]
 [ 0.04158554  0.01236259]
 [ 0.61298996  1.96737722]
 [-1.38692549 -1.45389838]
 [ 0.13681961  1.01862012]
 [ 0.89869216 -1.16639623]
 [-0.91075515  1.50737378]
 [-1.86309584 -0.53389149]
 [-0.24411666  0.58736689]
 [-1.10122329  0.27111453]
 [-0.24411666 -0.59139192]
 [ 0.23205368  0.12736345]
 [ 1.56533065  1.07612055]
 [ 0.04158554 -0.56264171]
 [ 0.99392623 -0.85014386]
 [-0.62505294  0.52986646]
 [ 0.99392623  0.73111797]
 [-1.29169142 -1.25264687]
 [-1.6726277   0.32861496]
 [-0.24411666  0.06986302]
 [-1.19645735  0.47236603]
 [-0.72028701  1.85237636]
 

In [9]:
print(X_test)

[[-1.6726277   0.09861324]
 [ 0.89869216 -0.62014214]
 [ 0.04158554 -0.1601387 ]
 [-0.62505294 -1.51139881]
 [ 0.04158554 -0.44764085]
 [ 0.32728775 -1.16639623]
 [-0.24411666 -0.50514128]
 [-1.00598922 -0.39014042]
 [-1.76786177 -1.42514816]
 [ 1.47009658  0.32861496]
 [ 0.42252182  0.55861668]
 [ 0.42252182 -0.47639106]
 [-0.72028701  1.30612227]
 [-0.72028701 -0.62014214]
 [-0.24411666 -0.39014042]
 [ 0.42252182 -0.1601387 ]
 [ 0.13681961  0.06986302]
 [ 1.75579879 -0.30388977]
 [-0.4345848  -0.04513784]
 [ 1.37486251 -1.42514816]
 [ 0.8034581  -0.33263999]
 [-1.48215956 -1.25264687]
 [-0.52981887  1.42112313]
 [ 1.0891603   0.09861324]
 [ 0.13681961  0.24236431]
 [-0.62505294  0.15611367]
 [-1.10122329  0.04111281]
 [ 0.13681961  1.82362614]
 [ 0.23205368 -0.30388977]
 [-0.05364853  2.11112829]
 [-0.4345848  -1.13764601]
 [ 1.18439437 -0.76389321]
 [-1.76786177 -0.01638762]
 [ 0.70822403  0.24236431]
 [ 0.8034581   0.09861324]
 [-0.33935073 -0.79264343]
 [ 2.13673506  0.90361926]
 

## Training the Logistic Regression model on the Training set

In [8]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 27)
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=27, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## Predicting a new result

In [10]:
print(classifier.predict(sc.transform([[30,87000]])))

[0]


## Predicting the Test set results

In [11]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]]


## Making the Confusion Matrix

In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[60  5]
 [10 25]]


0.85